/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package samples;

import javax.swing.JOptionPane;
import vector2d.Vector2D;

/**
 *
 * @author Oscar
 */
public class PhysicsCalc extends javax.swing.JFrame {

    /**
     * Creates new form PhysicsCalc
     */
    public PhysicsCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDotProduct = new javax.swing.JButton();
        btnCross = new javax.swing.JButton();
        btnAngle = new javax.swing.JButton();
        btnLength2 = new javax.swing.JButton();
        btnLength = new javax.swing.JButton();
        jtxtVarI = new javax.swing.JTextField();
        btnOneAngle = new javax.swing.JButton();
        jtxtVarj = new javax.swing.JTextField();
        iVarL = new javax.swing.JLabel();
        jVarL = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jVarL1 = new javax.swing.JLabel();
        jtxtVarI1 = new javax.swing.JTextField();
        btnOneAngle1 = new javax.swing.JButton();
        jtxtVarj1 = new javax.swing.JTextField();
        iVarL1 = new javax.swing.JLabel();
        btnLength1 = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDotProduct.setText("Dot");
        btnDotProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotProductActionPerformed(evt);
            }
        });

        btnCross.setText("Cross");
        btnCross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrossActionPerformed(evt);
            }
        });

        btnAngle.setText("Angle");
        btnAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngleActionPerformed(evt);
            }
        });

        btnLength2.setText("Length");
        btnLength2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLength2ActionPerformed(evt);
            }
        });

        btnLength.setText("Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        btnOneAngle.setText("Angle");
        btnOneAngle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneAngleActionPerformed(evt);
            }
        });

        iVarL.setText("i comp");

        jVarL.setText("j comp");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jVarL1.setText("j comp");

        btnOneAngle1.setText("Angle");
        btnOneAngle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneAngle1ActionPerformed(evt);
            }
        });

        iVarL1.setText("i comp");

        btnLength1.setText("Length");
        btnLength1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLength1ActionPerformed(evt);
            }
        });

        btnSubtract.setText("Minus");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOneAngle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtVarI)
                    .addComponent(jtxtVarj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jVarL)
                    .addComponent(iVarL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCross, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAngle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDotProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLength2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLength1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOneAngle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtVarI1)
                    .addComponent(jtxtVarj1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jVarL1)
                    .addComponent(iVarL1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtVarI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iVarL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtVarj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jVarL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOneAngle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLength))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtVarI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iVarL1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtVarj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jVarL1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOneAngle1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLength1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnDotProduct)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCross)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAngle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLength2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubtract)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrossActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        double kip = leftSide.vectorCrossPro2D(rightSide);
        JOptionPane.showMessageDialog(null, kip + "Cross Product");

    }//GEN-LAST:event_btnCrossActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        Vector2D kip = leftSide.vectorAdd2D(rightSide);
        JOptionPane.showMessageDialog(null, kip.getiA() + " i" + kip.getjA() + " j");

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnLength2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLength2ActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        double kip = leftSide.vectorLength2D(leftSide, rightSide);
        JOptionPane.showMessageDialog(null, kip + " Length");

    }//GEN-LAST:event_btnLength2ActionPerformed

    private void btnLength1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLength1ActionPerformed
        // TODO add your handling code here:
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        double kip = rightSide.vectorLength2D();
        JOptionPane.showMessageDialog(null, kip + " Length");

    }//GEN-LAST:event_btnLength1ActionPerformed

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        double kip = leftSide.vectorLength2D();
        JOptionPane.showMessageDialog(null, kip + " Length");

    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnDotProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotProductActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        double kip = leftSide.vectorDotProLen2D(rightSide);
        JOptionPane.showMessageDialog(null, kip + "Dot Product");

    }//GEN-LAST:event_btnDotProductActionPerformed

    private void btnOneAngle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneAngle1ActionPerformed
        // TODO add your handling code here:
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        double kip = rightSide.vectorAngle2D();
        JOptionPane.showMessageDialog(null, kip + " Degrees");

    }//GEN-LAST:event_btnOneAngle1ActionPerformed

    private void btnAngleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngleActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        double kip = leftSide.vectorDotProAngle2D(rightSide);
        JOptionPane.showMessageDialog(null, kip + " Degrees");

    }//GEN-LAST:event_btnAngleActionPerformed

    private void btnOneAngleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneAngleActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        double kip = leftSide.vectorAngle2D();
        JOptionPane.showMessageDialog(null, kip + "  Degrees");

    }//GEN-LAST:event_btnOneAngleActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        // TODO add your handling code here:
        leftSide = new Vector2D(Double.parseDouble(jtxtVarI.getText()), Double.parseDouble(jtxtVarj.getText()));
        rightSide = new Vector2D(Double.parseDouble(jtxtVarI1.getText()), Double.parseDouble(jtxtVarj1.getText()));
        leftSide.vecToSubtract2D(rightSide);
        JOptionPane.showMessageDialog(null, leftSide.getiA() + " i" + leftSide.getjA() + " j");
    }//GEN-LAST:event_btnSubtractActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editorfold - defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicsCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicsCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicsCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicsCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editorfold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsCalc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAngle;
    private javax.swing.JButton btnCross;
    private javax.swing.JButton btnDotProduct;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnLength1;
    private javax.swing.JButton btnLength2;
    private javax.swing.JButton btnOneAngle;
    private javax.swing.JButton btnOneAngle1;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JLabel iVarL;
    private javax.swing.JLabel iVarL1;
    private javax.swing.JLabel jVarL;
    private javax.swing.JLabel jVarL1;
    private javax.swing.JTextField jtxtVarI;
    private javax.swing.JTextField jtxtVarI1;
    private javax.swing.JTextField jtxtVarj;
    private javax.swing.JTextField jtxtVarj1;
    // End of variables declaration//GEN-END:variables
    static Vector2D leftSide = new Vector2D();
    static Vector2D rightSide = new Vector2D();
}
